/* config.js — дані (тримовні) + спільний простір імен IR */
window.IR = window.IR || {};

IR.SIT = {"1": {"ua": "Спільне споглядання заходу сонця", "en": "Watching the sunset", "pl": "WSPÓLNE OGLĄDANIE ZACHODU SŁOŃCA"}, "2": {"ua": "Провести разом ніч (секс)", "en": "Night together (sex)", "pl": "SPĘDZIĆ RAZEM NOC (SEX)"}, "3": {"ua": "Розмова про дитинство", "en": "Talking about childhood", "pl": "ROZMOWA O DZIECIŃSTWIE"}, "4": {"ua": "Спільний танець", "en": "Dance together", "pl": "WSPÓLNY TANIEC"}, "5": {"ua": "Купання голяка в морі", "en": "Bathing naked", "pl": "KĄPIEL NAGO W MORZU"}, "6": {"ua": "Дослідження печери", "en": "Visiting a cave", "pl": "ZWIEDZANIE JASKINI"}, "7": {"ua": "Лежання в гамаках", "en": "Lying in hammocks", "pl": "LEŻENIE NA HAMAKACH"}, "8": {"ua": "Будівництво куреня", "en": "Building a hut", "pl": "BUDOWANIE SZAŁASU"}, "9": {"ua": "Участь у богослужінні", "en": "A church service", "pl": "UDZIAŁ W NABOŻEŃSTWIE"}, "10": {"ua": "Випити рому", "en": "Drink rum", "pl": "NAPIĆ SIĘ RUMU"}, "11": {"ua": "Спів гімну", "en": "Singing the anthem", "pl": "ODŚPIEWANIE HYMNU"}, "12": {"ua": "Спільні плітки", "en": "Gossiping", "pl": "WSPÓLNE PLOTKI"}, "13": {"ua": "Лизати жабу", "en": "Licking a frog", "pl": "LIZANIE ŻABY"}, "14": {"ua": "Збирання гілок", "en": "Picking branches", "pl": "ZBIERANIE GAŁĘZI"}, "15": {"ua": "Приготування їжі", "en": "Preparing a meal", "pl": "PRZYGOTOWANIE POSIŁKU"}, "16": {"ua": "Збирання кокосів", "en": "Collecting coconuts", "pl": "ZBIERANIE KOKOSÓW"}, "17": {"ua": "Ловля риби", "en": "Fishing", "pl": "ŁOWIENIE RYB"}, "18": {"ua": "Миття посуду", "en": "Washing dishes", "pl": "MYCIE NACZYŃ"}, "19": {"ua": "Напис «SOS»", "en": "\"SOS\" on the beach", "pl": "NAPIS \"SOS\""}, "20": {"ua": "Збудувати вбиральню", "en": "Build a latrine", "pl": "ZBUDOWAĆ LATRYNĘ"}, "21": {"ua": "Розмова про політику", "en": "Talking politics", "pl": "ROZMOWA O POLITYCE"}, "22": {"ua": "Дати один одному по пиці", "en": "Roughhousing", "pl": "DAĆ SOBIE PO MORDZIE"}, "23": {"ua": "Уполювати кабана", "en": "Hunting a boar", "pl": "UPOLOWAĆ DZIKA"}, "24": {"ua": "Їсти черв'яків", "en": "Eating maggots", "pl": "JEŚĆ ROBAKI"}};

IR.REACTIONS = [{"pl": "ZŁOŚĆ", "en": "Anger", "ua": "Злість", "g": "neg"}, {"pl": "GNIEW", "en": "Rage", "ua": "Гнів", "g": "neg"}, {"pl": "PANIKA", "en": "Panic", "ua": "Паніка", "g": "neg"}, {"pl": "LĘK", "en": "Fear", "ua": "Страх", "g": "neg"}, {"pl": "AGRESJA", "en": "Aggression", "ua": "Агресія", "g": "neg"}, {"pl": "NIECHĘĆ", "en": "Reluctance", "ua": "Небажання", "g": "neg"}, {"pl": "ROZCZAROWANIE", "en": "Disappointment", "ua": "Розчарування", "g": "neg"}, {"pl": "ZDENERWOWANIE", "en": "Nervousness", "ua": "Нервування", "g": "neg"}, {"pl": "CIEKAWOŚĆ", "en": "Curiosity", "ua": "Цікавість", "g": "neu"}, {"pl": "OCZEKIWANIE", "en": "Expectancy", "ua": "Очікування", "g": "neu"}, {"pl": "OBOJĘTNOŚĆ", "en": "Indifference", "ua": "Байдужість", "g": "neu"}, {"pl": "UWAŻNOŚĆ", "en": "Attention", "ua": "Уважність", "g": "neu"}, {"pl": "ZADOWOLENIE", "en": "Contentment", "ua": "Задоволеність", "g": "neu"}, {"pl": "NADZIEJA", "en": "Hope", "ua": "Надія", "g": "neu"}, {"pl": "ZAINTERESOWANIE", "en": "Interest", "ua": "Зацікавленість", "g": "neu"}, {"pl": "GOTOWOŚĆ", "en": "Readiness", "ua": "Готовність", "g": "neu"}, {"pl": "PODNIECENIE", "en": "Excitement", "ua": "Збудження", "g": "pos"}, {"pl": "POŻĄDANIE", "en": "Desire", "ua": "Бажання", "g": "pos"}, {"pl": "EKSCYTACJA", "en": "Excitation", "ua": "Захват", "g": "pos"}, {"pl": "SATYSFAKCJA", "en": "Satisfaction", "ua": "Задоволення", "g": "pos"}, {"pl": "EUFORIA", "en": "Euphoria", "ua": "Ейфорія", "g": "pos"}, {"pl": "MIŁOŚĆ", "en": "Love", "ua": "Любов", "g": "pos"}, {"pl": "ZAKOCHANIE", "en": "Infatuation", "ua": "Закоханість", "g": "pos"}, {"pl": "SZCZĘŚCIE", "en": "Happiness", "ua": "Щастя", "g": "pos"}];
IR.RGROUP = {neg:"#29b6e8", neu:"#54c46a", pos:"#ef5350"};

IR.DECKS = [{"c": "#e8483f", "n": {"ua": "Червона", "en": "Red", "pl": "Czerwona"}, "file": "RedCover.png"}, {"c": "#2aa4d6", "n": {"ua": "Синя", "en": "Blue", "pl": "Niebieska"}, "file": "BlueCover.png"}, {"c": "#46b257", "n": {"ua": "Зелена", "en": "Green", "pl": "Zielona"}, "file": "GreenCover.png"}, {"c": "#f2c200", "n": {"ua": "Жовта", "en": "Yellow", "pl": "Żółta"}, "file": "YellowCover.png"}, {"c": "#ef7d1a", "n": {"ua": "Помаранчева", "en": "Orange", "pl": "Pomarańczowa"}, "file": "OrangeCover.png"}, {"c": "#1fa59a", "n": {"ua": "Бірюзова", "en": "Turquoise", "pl": "Turkusowa"}, "file": "GreenWhiteCover.png"}];

IR.SAND = {xmin:40,xmax:58,ymin:60,ymax:78};
IR.DEFAULT_CELLS = [{"x":0.4776,"y":0.8296},{"x":0.3487,"y":0.8172},{"x":0.2118,"y":0.7801},{"x":0.125,"y":0.7209},{"x":0.1,"y":0.6205},{"x":0.1447,"y":0.5393},{"x":0.2118,"y":0.4733},{"x":0.2934,"y":0.4265},{"x":0.3579,"y":0.3563},{"x":0.3224,"y":0.2298},{"x":0.3197,"y":0.1431},{"x":0.375,"y":0.1059},{"x":0.4526,"y":0.0977},{"x":0.5395,"y":0.1403},{"x":0.5908,"y":0.2229},{"x":0.6487,"y":0.282},{"x":0.7263,"y":0.3329},{"x":0.8066,"y":0.3893},{"x":0.8605,"y":0.4609},{"x":0.8895,"y":0.5324},{"x":0.8974,"y":0.5929},{"x":0.8842,"y":0.6645},{"x":0.8342,"y":0.7484},{"x":0.7474,"y":0.7952},{"x":0.5947,"y":0.8103}];
IR.cells = null;
IR.mode  = 'play';
IR.cfg   = {mode:'game', humans:4, widmo:false, widmos:0, picks:[]};

IR.util = {
  sleep: ms => new Promise(r=>setTimeout(r,ms)),
  pad: n => (n<10?'0':'')+n,
  addDot(overlay,p,i){const d=document.createElement('div');d.className='cellDot';
    d.style.left=(p.x*100)+'%';d.style.top=(p.y*100)+'%';d.textContent=i;overlay.appendChild(d);}
};
